

from typing import Optional, List, Dict
from enum import Enum
from datetime import datetime

from pydantic import BaseModel
from scipy.integrate._ivp.ivp import OdeResult
from numpy import pi, linspace



###############################################################################
################### Schemas needed in main.py and tasks.py ####################
###############################################################################

class SimSystem(str, Enum):
    """List of available systems for simulation.
    
    Notes
    -----
    CAUTION: This list must coincide with the dictionary list `Simulations`
    defined in __init__.py in the module simulations, otherwise the system
    won't be simulated by the backend.
    """
    Harmonic_Oscillator = "Harmonic-Oscillator"
    Quantum_Harmonic_Oscillator = "Quantum-Harmonic-Oscillator"


class IntegrationMethods(str, Enum):
    """List of available integration methods"""
    RK45 = "RK45"
    RK23 = "RK23"


class HOParams(BaseModel):
    """List of parameters of the Harmonic Oscillator system"""
    m: float    # Mass
    k: float    # Force constant


class SimRequest(BaseModel):
    """Schema needed to request harmonic oscillator simulations
    
    Most of the attributes in this pydantic class are arguments of the
    `HarmonicOsc1D.__init__` method. See `HarmonicOsc1D` documentation
    in simulation.py to understand them. 
    """
    system: SimSystem = SimSystem.Harmonic_Oscillator
    t_span: Optional[List[float]] = [0, 2 * pi]
    t_eval: Optional[List[float]] = list(linspace(0, 2 * pi, 20))
    ini_cndtn: Optional[List[float]] = [1, 0]
    params: Optional[HOParams] = HOParams(m=1, k=1)
    method: Optional[IntegrationMethods] = 'RK45'
    # The backend will assign a sim_id, so it is not necessary to provide one.
    sim_id: Optional[str] = None
    # If we implement logging, user_id will be handled by backend
    user_id: Optional[int]
    username: str = "Pepito Perez"


class SimIdResponse(BaseModel):
    """Schema for the response of a simulation request via POST to route
    "/api/simulate/{sim_sys}"
    """
    sim_id : str
    user_id : int
    username : str
    sim_system : SimSystem
    sim_status_path : str
    sim_pickle_path : str
    message : Optional[str]


class SimResults(BaseModel):
    """Results of simulation as returned by scipy.integrate.solve_ivp"""
    sim_results: OdeResult


class SimStatus(BaseModel):
    """Schema of the status of simulations

    This pydantic model is intended to store paths of results of the simulations
    algong with some metadata. This is what the API returns when someone
    requests a simulation via /api/simulate/{system}/ with method=post.
    
    Atributes
    ---------
    sim_id : int
        ID number of simulation.
    user_id : int
        User id number stored in database.
    date : datetime
        Late of request of simulation
    system : SimSystem
        Simulated system
    route_pickle : str
        Route of pickle file generated by the simulation backend.
    route_results : str
        Route of frontend showing results.
    route_plot : list
        Route of plots generated by the simulation backend.
    plot_query_values : list of strings
        Query params values of different automatically generated plots.
        These values are needed to download the plots. 
    success : bool
        Success status of simulation.
    message : str
        Additional information on status of simulation.
    """
    # User-related attributes
    sim_id: str
    user_id : int
    date: datetime

    # Simulation-related attributes
    system: SimSystem
    ini_cndtn: Optional[List[float]]
    params: Optional[Dict[str, float]]
    method: Optional[IntegrationMethods]

    # Response-related attributes
    route_pickle: Optional[str]
    route_results: Optional[str]
    route_plots: Optional[str]
    plot_query_values: Optional[List[str]]
    success : bool
    message : Optional[str]




###############################################################################
################### Schemas needed for databse interaction ####################
###############################################################################

############################ Users ############################
class UserDBSchBase(BaseModel):
    username: Optional[str]


class UserDBSch(UserDBSchBase):
    user_id : Optional[int]
    # This is needed to include (when reading) database relations created by ORM in sqlalchemy  
    # Read more in FastAPI docs: https://fastapi.tiangolo.com/tutorial/sql-databases/#use-pydantics-orm_mode   
    class Config:
        orm_model = True


class UserDBSchCreate(BaseModel):
    # Just for now store Null hash TODO TODO TODO change when logging
    # Production username and hash_value must be mandatory
    username : str
    hash_value: Optional[str]
    pass


############################ Simulation status ############################
class SimulationDBSchBase(BaseModel):
    sim_id: Optional[str]
    user_id: Optional[int]
    date: Optional[str]
    system: Optional[str]
    method: Optional[str]
    route_pickle: Optional[str]
    route_results: Optional[str]
    route_plots: Optional[str]
    success: Optional[bool]
    message: Optional[str]


class SimulationDBSch(SimulationDBSchBase):
    # This is needed to include (when reading) database relations created by ORM in sqlalchemy  
    # Read more in FastAPI docs: https://fastapi.tiangolo.com/tutorial/sql-databases/#use-pydantics-orm_mode   
    class Config:
        orm_model = True


class SimulationDBSchCreate(SimulationDBSchBase):
    sim_id: str
    user_id: int
    date: str
    system: str
    success: bool
    

############################ Plots ############################
class PlotDBSchBase(BaseModel):
    sim_id: Optional[str]
    plot_query_value: Optional[str]


class PlotDBSch(PlotDBSchBase):
    plot_id: Optional[int]
    # This is needed to include (when reading) database relations created by ORM in sqlalchemy  
    # Read more in FastAPI docs: https://fastapi.tiangolo.com/tutorial/sql-databases/#use-pydantics-orm_mode   
    class Config:
        orm_model = True


class PlotDBSchCreate(PlotDBSchBase):
    sim_id: str
    plot_query_value: str


############################ Parameters ############################
class ParamType(str, Enum):
    ini_cndtn = "initial condition"
    param = "parameter"


class ParameterDBSchBase(BaseModel):
    sim_id: Optional[str]
    param_type: Optional[ParamType]
    param_key: Optional[str]
    ini_cndtn_id: Optional[int]
    value: Optional[float]


class ParameterDBSch(ParameterDBSchBase):
    param_id: Optional[int]
    # This is needed to include (when reading) database relations created by ORM in sqlalchemy  
    # Read more in FastAPI docs: https://fastapi.tiangolo.com/tutorial/sql-databases/#use-pydantics-orm_mode   
    class Config:
        orm_model = True


class ParameterDBSchCreate(ParameterDBSchBase):
    sim_id: str
    param_type: ParamType
    value: float
